package main

func seedTransaksi(){
    dbTransaksi[0] = transaksi{
        riwayat: [NMAX]detailPembelian{
            {nilaiAset: 27400000,
             nilaiReturn: 128506000,
             jumlah: 10000,
             produk: "ANTM",
             tipe: "Saham",
             portofolio: "Tabungan",
             untung: 4.69,
             tanggal: "01-03-2025",
             tanda: 1},

            {nilaiAset: 30800000,
             nilaiReturn: 16940000,
             jumlah: 10000,
             produk: "PTRO",
             tipe: "Saham",
             portofolio: "Tabungan",
             untung: 0.55,
             tanggal: "05-03-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5620000,
             jumlah: 100,
             produk: "BRI Seruni Pasar Uang III",
             tipe: "Reksadana PasarUang",
             portofolio: "Dana Darurat",
             untung: 5.62,
             tanggal: "10-03-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 6500000,
             jumlah: 1,
             produk: "FR0081",
             tipe: "Obligasi",
             portofolio: "Tabungan",
             untung: 6.50,
             tanggal: "15-03-2025",
             tanda: 1},

            {nilaiAset: 1760000,
             nilaiReturn: 29163200,
             jumlah: 10000,
             produk: "DMAS",
             tipe: "Saham",
             portofolio: "Dana Darurat",
             untung: 16.57,
             tanggal: "20-03-2025",
             tanda: 1},

            {nilaiAset: 5000000,
             nilaiReturn: 22750000,
             jumlah: 100,
             produk: "Principal Cash Fund",
             tipe: "Reksadana PasarUang",
             portofolio: "Tabungan",
             untung: 4.55,
             tanggal: "25-03-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5370000,
             jumlah: 1,
             produk: "PBS036",
             tipe: "Obligasi",
             portofolio: "Tabungan",
             untung: 5.37,
             tanggal: "28-03-2025",
             tanda: 1},
        },
    }

    dbTransaksi[1] = transaksi{
        riwayat: [NMAX]detailPembelian{
            {nilaiAset: 64250000,
             nilaiReturn: 5782500,
             jumlah: 10000,
             produk: "BREN",
             tipe: "Saham",
             portofolio: "Dana Pensiun",
             untung: 0.09,
             tanggal: "11-04-2025",
             tanda: 1},

            {nilaiAset: 10000000,
             nilaiReturn: -4600000,
             jumlah: 100,
             produk: "Grow Saham Indonesia Plus Kelas O",
             tipe: "Reksadana Saham",
             portofolio: "Dana Pensiun",
             untung: -0.46,
             tanggal: "15-04-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5500000,
             jumlah: 1,
             produk: "FR0086",
             tipe: "Obligasi",
             portofolio: "Dana Pensiun",
             untung: 5.50,
             tanggal: "18-04-2025",
             tanda: 1},

            {nilaiAset: 89750000,
             nilaiReturn: 2692500,
             jumlah: 10000,
             produk: "CUAN",
             tipe: "Saham",
             portofolio: "Dana Darurat",
             untung: 0.03,
             tanggal: "20-04-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: -510000,
             jumlah: 100,
             produk: "Avrist IDX30",
             tipe: "Reksadana Saham",
             portofolio: "Dana Darurat",
             untung: -0.51,
             tanggal: "22-04-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 4870000,
             jumlah: 1,
             produk: "PBS032",
             tipe: "Obligasi",
             portofolio: "Dana Pensiun",
             untung: 4.87,
             tanggal: "25-04-2025",
             tanda: 1},
        },
    }

    dbTransaksi[2] = transaksi{
        riwayat: [NMAX]detailPembelian{
            {nilaiAset: 640000,
             nilaiReturn: 998400,
             jumlah: 10000,
             produk: "HUMI",
             tipe: "Saham",
             portofolio: "Liburan Keluarga",
             untung: 1.56,
             tanggal: "01-05-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5300000,
             jumlah: 100,
             produk: "Majoris Pasar Uang Syariah Indonesia",
             tipe: "Reksadana PasarUang",
             portofolio: "Dana Pendidikan",
             untung: 5.30,
             tanggal: "05-05-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 6000000,
             jumlah: 1,
             produk: "PBS003",
             tipe: "Obligasi",
             portofolio: "Data Investasi",
             untung: 6.00,
             tanggal: "08-05-2025",
             tanda: 1},

            {nilaiAset: 1750000,
             nilaiReturn: 28840000,
             jumlah: 10000,
             produk: "TASA",
             tipe: "Saham",
             portofolio: "Liburan Keluarga",
             untung: 16.48,
             tanggal: "10-05-2025",
             tanda: 1},

            {nilaiAset: 10000000,
             nilaiReturn: 63900000,
             jumlah: 100,
             produk: "ABF Indonesia Bond Index Fund",
             tipe: "Reksadana Obligasi",
             portofolio: "Dana Pendidikan",
             untung: 6.39,
             tanggal: "12-05-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5120000,
             jumlah: 1,
             produk: "FR0090",
             tipe: "Obligasi",
             portofolio: "Data Investasi",
             untung: 5.12,
             tanggal: "15-05-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: 5470000,
             jumlah: 100,
             produk: "Danamas Stabil",
             tipe: "Reksadana Obligasi",
             portofolio: "Liburan Keluarga",
             untung: 5.47,
             tanggal: "18-05-2025",
             tanda: 1},

            {nilaiAset: 1000000,
             nilaiReturn: -330000,
             jumlah: 10,
             produk: "Eastspring IDX ESG Leaders Plus Kelas A",
             tipe: "Reksadana Saham",
             portofolio: "Dana Pendidikan",
             untung: -0.33,
             tanggal: "20-05-2025",
             tanda: 1},
        },
    }
}